In [6]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.2


Introduction to Tensors

Creating tensors

In [10]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [11]:
scalar.ndim

0

In [12]:
# Gat tensor back as Python int
scalar.item()

7

In [14]:
# Vector
vector = torch.tensor([2,7])
vector

tensor([2, 7])

In [17]:
vector.ndim

1

In [19]:
vector.shape

torch.Size([2])

In [22]:
# Matrix
matrix = torch.tensor([[2,1],[3,0]])
matrix

tensor([[2, 1],
        [3, 0]])

In [23]:
 matrix.ndim

2

In [30]:
matrix[0,0]

tensor(2)

In [31]:
matrix.shape

torch.Size([2, 2])

In [53]:
# Tensor

tensor = torch.tensor([[[1,2,3,2],[3,6,9,2],[2,4,5,3]], [[1,2,3,6],[3,2,1,7],[2,1,3,1]] ])
tensor


tensor([[[1, 2, 3, 2],
         [3, 6, 9, 2],
         [2, 4, 5, 3]],

        [[1, 2, 3, 6],
         [3, 2, 1, 7],
         [2, 1, 3, 1]]])

In [54]:
tensor.ndim

3

In [55]:
tensor.shape

torch.Size([2, 3, 4])

Random tensor

In [56]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7271, 0.7128, 0.2565, 0.9408],
        [0.0091, 0.0653, 0.7660, 0.8156],
        [0.9540, 0.8476, 0.3228, 0.6017]])

In [57]:
random_tensor.ndim

2

In [58]:
random_tensor.shape

torch.Size([3, 4])

In [59]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

Zeros and ones

In [63]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [67]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [68]:
ones.dtype

torch.float32

In [70]:
zeros.dtype

torch.float32

Creating a range of tensors and tensors-like

In [83]:
# Use torch.range() use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor datatypes

In [100]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None, 
                               device="cpu",
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [104]:
float_32_tensor.dtype

torch.float32

In [105]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [108]:
float_none_tensor = float_16_tensor * float_32_tensor
float_none_tensor.dtype

torch.float32

In [109]:
float_none2_tensor = float_16_tensor * float_16_tensor
float_none2_tensor.dtype

torch.float16